#!/bin/bash

# Commands to run automatically
# sudo cp ~/.config/system/us /usr/share/X11/xkb/symbols/
# setxkbmap -layout us -variant intl_nodeadkeys
# xinput set-button-map 'Kensington Expert Mouse' 1 2 3 4 5 6 7 3
# zellij delete-all-sessions


# Default home directories
mkdir -p ~/{Appimage,Security,Workbench}
mkdir -p ~/.gnupg
mkdir -p ~/.ssh/keys
mkdir -p ~/.local/share/fonts

# GNOME Settings
gsettings set org.gnome.desktop.peripherals.touchpad tap-and-drag-lock true

# Volatile space
mkdir -p /tmp/Volatile
  if [ ! -f "~/Volatile" ]; then
      ln -s /tmp/Volatile ~/ 2>/dev/null
  fi

# Host or Toolbox autoruns
  if [ -f "/run/.toolboxenv" ]; then
    # Toolbox Environment
    echo
  else
    # Host Environment
    echo
    # Install local AI environment
    if ! [[ $(podman start ollama 2>/dev/null) ]]; then
        podman run -d -v ollama:/root/.ollama -p 11434:11434 --restart always --name ollama docker.io/ollama/ollama:latest
        podman exec -it ollama ollama pull llama3.2
    fi

    if ! [[ $(podman start open-webui 2>/dev/null) ]]; then
        podman run -d --network=host -v open-webui:/app/backend/data -e OLLAMA_BASE_URL=http://127.0.0.1:11434 --restart always --name open-webui ghcr.io/open-webui/open-webui:latest
    fi
  fi

# Clear before display
cls
