    name: Clean_Images
    on:
      schedule:
        - cron: '05 11 * * *'
      workflow_dispatch:

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

    jobs:
      delete-older-than-5:
        runs-on: ubuntu-latest
        permissions:
          packages: write
        steps:
          - name: Delete Images Older Than 5 Days
            uses: dataaxiom/ghcr-cleanup-action@v1.0.16
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              packages: simplis
              older-than: 5 days
              delete-orphaned-images: true
              keep-n-tagged: 5
              keep-n-untagged: 5
              #dry-run: true
